apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: minikube-k8s-lab
      volumes:
        - name: nginx-html-volume
          persistentVolumeClaim:
            claimName: nginx-html-pvc
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-html-volume
              mountPath: /usr/share/nginx/html
      initContainers:
        - name: nginx-init
          image: busybox:1.36
          command: ['sh', '-c', 'echo "<p>Pod iniciado em: $(date)</p>" >> /data/index.html']
          volumeMounts:
            - name: nginx-html-volume
              mountPath: /data
