apiVersion: v1
kind: Secret
metadata:
  name: nginx-auth-file
type: Opaque
data:
  .htpasswd: YWRtaW46ZmNEYTQ4SklBeGY5dwo=

---

apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret-vars
type: Opaque
data:
  API_TOKEN: bWV1LXRva2VuLXN1cGVyLXNlY3JldG8=
  