apiVersion: v1
kind: Namespace
metadata:
  name: lab-storage

---

apiVersion: v1
kind: Namespace
metadata:
  name: lab-config

---

apiVersion: v1
kind: Namespace
metadata:
  name: lab-health

---

apiVersion: v1
kind: Namespace
metadata:
  name: lab-scaling
  